"""Application settings.

Shim retrocompatibile: i valori vengono dalla config centralizzata
(`utils/config.py`, pydantic BaseSettings con prefisso SOPHIA_VECTOR_).
Questo modulo mantiene i nomi delle costanti storiche così il codice che
fa `from utils.settings import QDRANT_URL` non cambia.
"""

from utils.config import settings

# Qdrant & servizi
QDRANT_URL = settings.QDRANT_URL
DOCLING_URL = settings.DOCLING_URL
DOCLING_CLEAR_EVERY = settings.DOCLING_CLEAR_EVERY
MONGODB_DB_URI = settings.MONGODB_URI
BGE_M3_URL = settings.EMBEDDINGS_URL

# FalkorDB (knowledge graph)
GRAPH_ENABLED = settings.GRAPH_ENABLED
FALKOR_HOST = settings.FALKOR_HOST
FALKOR_PORT = settings.FALKOR_PORT
FALKOR_PASSWORD = settings.FALKOR_PASSWORD
FALKOR_GRAPH_PREFIX = settings.FALKOR_GRAPH_PREFIX

# Entity extraction (GLiNER + regex)
GLINER_ENABLED = settings.GLINER_ENABLED
GLINER_MODEL = settings.GLINER_MODEL
GLINER_THRESHOLD = settings.GLINER_THRESHOLD
GLINER_LABELS = [s.strip() for s in settings.GLINER_LABELS.split(",") if s.strip()]
GLINER_DEVICE = settings.GLINER_DEVICE

# Relation extraction (GLiNER-relex, archi tipizzati)
RELATIONS_ENABLED = settings.RELATIONS_ENABLED
RELATIONS_MODEL = settings.RELATIONS_MODEL
RELATIONS_ENTITY_THRESHOLD = settings.RELATIONS_ENTITY_THRESHOLD
RELATIONS_THRESHOLD = settings.RELATIONS_THRESHOLD
RELATIONS_ADJACENCY_THRESHOLD = settings.RELATIONS_ADJACENCY_THRESHOLD
RELATIONS_LABELS = [s.strip() for s in settings.RELATIONS_LABELS.split(",") if s.strip()]
RELATIONS_MAX_ENTITY_WORDS = settings.RELATIONS_MAX_ENTITY_WORDS
RELATIONS_DROP_OTHER_TO_OTHER = settings.RELATIONS_DROP_OTHER_TO_OTHER

CLASSIFIER_ENABLED = settings.CLASSIFIER_ENABLED
CLASSIFIER_MODEL = settings.CLASSIFIER_MODEL
CLASSIFIER_THRESHOLD = settings.CLASSIFIER_THRESHOLD
CLASSIFIER_MULTI_LABEL = settings.CLASSIFIER_MULTI_LABEL
CLASSIFIER_LABELS = [s.strip() for s in settings.CLASSIFIER_LABELS.split(",") if s.strip()]

# Storage
FILES_STORAGE = settings.FILES_STORAGE
DOCUMENTS_STORAGE = settings.DOCUMENTS_STORAGE
MAX_FILE_SIZE = settings.MAX_FILE_SIZE_MB * 1024 * 1024

# Chunking
DEFAULT_CHUNK_SIZE = settings.DEFAULT_CHUNK_SIZE
DEFAULT_CHUNK_OVERLAP = settings.DEFAULT_CHUNK_OVERLAP
DEFAULT_EMBEDDING_DIMENSION = settings.DEFAULT_EMBEDDING_DIMENSION
DEFAULT_POINTS_BATCH_SIZE = settings.DEFAULT_POINTS_BATCH_SIZE

# Parser Docling (tuning)
PARSER_MODEL_TOKENIZER = settings.PARSER_MODEL_TOKENIZER
PARSER_MODEL_MAX_TOKENS = settings.PARSER_MODEL_MAX_TOKENS
PARSER_USE_OCR = settings.PARSER_USE_OCR
PARSER_PICTURE_DESCRIPTION = settings.PARSER_PICTURE_DESCRIPTION
PARSER_TABLE_MODE = settings.PARSER_TABLE_MODE.lower()
PARSER_TABLE_CELL_MATCHING = settings.PARSER_TABLE_CELL_MATCHING
PARSER_PDF_BACKEND = settings.PARSER_PDF_BACKEND.lower()
PARSER_MAX_WAIT_SECONDS = settings.PARSER_MAX_WAIT_SECONDS

# Tabular ingestion (CSV/XLSX): chunker dedicato (vedi utils/tabular.py)
TABULAR_ENABLED = settings.TABULAR_ENABLED
TABULAR_ROWS_PER_CHUNK = settings.TABULAR_ROWS_PER_CHUNK
TABULAR_MAX_ROW_CHUNKS = settings.TABULAR_MAX_ROW_CHUNKS
TABULAR_SAMPLE_ROWS = settings.TABULAR_SAMPLE_ROWS
TABULAR_TOP_CATEGORIES = settings.TABULAR_TOP_CATEGORIES
TABULAR_MAX_READ_MB = settings.TABULAR_MAX_READ_MB

# ASR (trascrizione audio/video, faster-whisper)
ASR_ENABLED = settings.ASR_ENABLED
ASR_MODEL = settings.ASR_MODEL
ASR_LANGUAGE = settings.ASR_LANGUAGE
ASR_DEVICE = settings.ASR_DEVICE
ASR_COMPUTE_TYPE = settings.ASR_COMPUTE_TYPE
ASR_MAX_AUDIO_MINUTES = settings.ASR_MAX_AUDIO_MINUTES
ASR_MAX_VIDEO_MINUTES = settings.ASR_MAX_VIDEO_MINUTES

# Data curation (dedup del contenuto)
CURATION_ENABLED = settings.CURATION_ENABLED
CURATION_GRAPH_LINK = settings.CURATION_GRAPH_LINK
CURATION_BOILERPLATE_RATIO = settings.CURATION_BOILERPLATE_RATIO
CURATION_BOILERPLATE_MIN_DOCS = settings.CURATION_BOILERPLATE_MIN_DOCS

# Quality scoring euristico dei chunk (vedi utils/quality.py)
QUALITY_ENABLED = settings.QUALITY_ENABLED
QUALITY_MIN_WORDS = settings.QUALITY_MIN_WORDS
QUALITY_SEARCH_MIN = settings.QUALITY_SEARCH_MIN

# Ingestion worker (tuning)
INGEST_BATCH_SIZE = settings.INGEST_BATCH_SIZE
INGEST_MAX_CONCURRENT_JOBS = settings.INGEST_MAX_CONCURRENT_JOBS
INGEST_WAIT_TIME_JOBS = settings.INGEST_WAIT_TIME_JOBS
SHAREPOINT_POLL_INTERVAL = settings.SHAREPOINT_POLL_INTERVAL

# Scheduler (cron interno)
INTERNAL_API_URL = settings.INTERNAL_API_URL
SCHEDULER_POLL_INTERVAL = settings.SCHEDULER_POLL_INTERVAL
SCHEDULER_TZ = settings.SCHEDULER_TZ
